backend:
  name: git-gateway
  branch: main # Change to 'master' if your branch is named master

media_folder: "images/uploads" # Where uploaded images will be stored
public_folder: "/images/uploads" # Public path to uploaded images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
